In [1]:
from sklearn.preprocessing import MinMaxScaler

data = [[-1,2], [-0.5, 6], [0, 10],[1, 18]]
data

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [2]:
import pandas as pd
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [3]:
#实现归一化
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
result_ = scaler.fit_transform(data) # 训练和导出结果一步达成

scaler.inverse_transform(result) # 结果逆转

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [5]:
# MinMaxScaler 的参数 feature_range 实现数据归一化到【0，1】以外的数据

scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [ ]:
#当X中的特征数量非常多的时候，fit会报错
#使用partial_fit 作为训练接口
#scaler = scaler.partial_fit(data)

In [6]:
# 归一化
import numpy as np

X = np.array(data)

X_norm = (X - X.min(axis=0))/ (X.max(axis=0) - X.min(axis=0))
X_norm

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [7]:
# 逆转归一化

X_returned = X_norm *(X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(data)

StandardScaler()

In [11]:
scaler.mean_

array([-0.125,  9.   ])

In [12]:
scaler.var_

array([ 0.546875, 35.      ])

In [13]:
x_std = scaler.transform(data)

In [14]:
x_std.mean()

0.0

In [15]:
x_std.std()

1.0

In [16]:
scaler.fit_transform(data)
scaler.inverse_transform(x_std )

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])