In [1]:
import torch
import numpy as np

### pytorch和numpy数据转化

In [2]:
np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)
torch_to_array = torch_data.numpy()

print('\nnumpy:\n', np_data,
      '\ntorch:\n',torch_data,
      '\ntorch_to_arrray:\n',torch_to_array)


numpy:
 [[0 1 2]
 [3 4 5]] 
torch:
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
torch_to_arrray:
 [[0 1 2]
 [3 4 5]]


### 运算符

In [3]:
#abs sin mean
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print('\nabs:',
      '\nnumpy:',np.abs(data),
      '\ntorch',torch.abs(tensor),
      '\nsin',
      '\nnumpy:',np.sin(data),
      '\ntorch',torch.sin(tensor))


abs: 
numpy: [1 2 1 2] 
torch tensor([1., 2., 1., 2.]) 
sin 
numpy: [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch tensor([-0.8415, -0.9093,  0.8415,  0.9093])


### 矩阵运算

In [4]:
data = [[1,2],[3,4]]
tensor = torch.FloatTensor(data)
data = np.array(data)
## 矩阵乘法
print(
    '\nnumpy',np.matmul(data,data),
    '\nnumpy',data.dot(data),
    '\ntorch',torch.mm(tensor,tensor),
)


numpy [[ 7 10]
 [15 22]] 
numpy [[ 7 10]
 [15 22]] 
torch tensor([[ 7., 10.],
        [15., 22.]])
